{{- $root := . -}}
{{- range $idx, $dep := .Values.deployments }}
  {{- $ingEnabled := false -}}
  {{- $ingVals := dict -}}
  
  {{- if and $dep.ingress (hasKey $dep.ingress "enabled") }}
    {{- $ingEnabled = $dep.ingress.enabled -}}
    {{- $ingVals = $dep.ingress -}}
  {{- else if $root.Values.ingress.enabled }}
    {{- $ingEnabled = true -}}
    {{- $ingVals = $root.Values.ingress -}}
  {{- end }}

  {{- if $ingEnabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "KubeKit.fullname" $root }}-{{ $dep.name }}
  labels:
    {{- include "KubeKit.labels" $root | nindent 4 }}
  {{- with $ingVals.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $ingVals.className }}
  ingressClassName: {{ $ingVals.className }}
  {{- end }}
  rules:
    {{- range $ingVals.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "KubeKit.fullname" $root }}-{{ $dep.name }}-service
                port:
                  number: {{ .servicePort | default 80 }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}