{{- if .Values.persistence.enabled }}
{{- range .Values.persistence.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "KubeKit.fullname" $ }}-{{ .name }}-pvc
  labels:
    {{- include "KubeKit.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .accessMode | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
  {{- if .storageClass }}
  storageClassName: {{ .storageClass | quote }}
  {{- end }}
{{- end }}
{{- end }}